#!/usr/bin/env bash
# Proposes a per-task CODE_MODEL / REVIEW_MODEL choice for every unchecked
# claude-workflow/PLAN.md task, biased hard toward the cheapest model that
# can do the job. Writes claude-workflow/MODEL_PLAN.md for human review —
# nothing here is auto-applied. run-plan.sh only uses MODEL_PLAN.md's
# choices if you keep the file after reviewing/editing it; delete it to
# fall back to the static CODE_MODEL / REVIEW_MODEL variables in run-plan.sh.
# Usage: bash claude-workflow/classify-models.sh
set -uo pipefail

PROJECT_DIR="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
cd "$PROJECT_DIR"

WORKFLOW_DIR="claude-workflow"
PLAN_FILE="$WORKFLOW_DIR/PLAN.md"
OUT_FILE="$WORKFLOW_DIR/MODEL_PLAN.md"
CLASSIFIER_MODEL="claude-haiku-4-5-20251001"

log() { echo "[classify-models] $*"; }

if [ ! -f "$PLAN_FILE" ]; then
  log "ERROR: $PLAN_FILE not found."
  exit 1
fi

{
  echo "# MODEL_PLAN.md — proposed per-task model choices"
  echo ""
  echo "Generated by classify-models.sh, using $CLASSIFIER_MODEL as the classifier."
  echo "REVIEW AND EDIT before running run-plan.sh — it trusts this file as-is."
  echo "Delete this file to fall back to run-plan.sh's static CODE_MODEL / REVIEW_MODEL."
  echo ""
} > "$OUT_FILE"

TASK_COUNT=0
while IFS= read -r line; do
  TASK_TEXT="${line#"- [ ] "}"
  [ -z "$TASK_TEXT" ] && continue
  TASK_COUNT=$((TASK_COUNT + 1))

  log "Classifying task $TASK_COUNT: ${TASK_TEXT:0:60}..."

  RESPONSE=$(claude -p "You are choosing which Claude model should CODE this task and
which should REVIEW its diff afterward. Available models, cheapest to most
expensive:
- claude-haiku-4-5-20251001 (cheapest — mechanical edits, config/data
  changes, boilerplate, single-file changes with no real logic)
- claude-sonnet-5 (mid — real logic, multi-file changes, anything touching
  application behavior)
- claude-opus-4-8 (most expensive — security, payments, auth, migrations,
  concurrency, or anything where a subtle bug is costly)

DEFAULT TO THE CHEAPEST MODEL THAT CAN RELIABLY DO THE JOB. Only escalate
when the task genuinely needs it — do not escalate out of caution alone.
The review model should usually be the same as or cheaper than the code
model, since it only reads a diff — escalate the review model only if the
diff is likely to touch security/payments/auth.

Task: $TASK_TEXT

Respond with ONLY this exact format, nothing else:
code_model: <model id>
review_model: <model id>
reason: <one sentence>" \
    --model "$CLASSIFIER_MODEL" \
    --permission-mode acceptEdits 2>/dev/null)

  {
    echo "## Task: $TASK_TEXT"
    echo "$RESPONSE" | grep -E '^(code_model|review_model|reason):' | sed 's/^/- /'
    echo ""
  } >> "$OUT_FILE"

done < <(grep -E '^- \[ \]' "$PLAN_FILE")

if [ "$TASK_COUNT" -eq 0 ]; then
  log "No unchecked tasks found in $PLAN_FILE — nothing to classify."
  exit 0
fi

log "Wrote $OUT_FILE ($TASK_COUNT tasks). Review it, then run: bash claude-workflow/run-plan.sh"
